FROM golang:1.19.4 as builder
WORKDIR /app/
ENV GO111MODULE=on

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go build -o bin/main main.go

FROM ubuntu:20.04  
RUN apt update && apt install -y \
    curl \
    ca-certificates
WORKDIR /app/
COPY --from=builder /app/bin/main .
COPY --from=builder /app/app/account/public/views/send_code_with_email.html /app/app/account/public/views/send_code_with_email.html
COPY --from=builder /app/keys /app/keys
